---
- name: Ensure Homebrew is installed
  shell: |
    if ! command -v brew >/dev/null 2>&1; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
  args:
    executable: /bin/bash
  changed_when: false

- name: Install Homebrew packages
  shell: |
    if ! brew list --versions {{ item }} >/dev/null 2>&1; then
      brew install {{ item }}
    fi
  loop: "{{ brew_packages }}"
  changed_when: false
