name: <%= args[0] %>
root: ~/Projects/<%= @args[0] %>

windows:
  - editors:
      layout: even-horizontal
      panes:
        - nvim
        - nvim
  - servers:
      layout: even-horizontal
      panes:
        - ll
        - rs
