---
- name: Ensure ~/.config exists
  file:
    path: "{{ home }}/.config"
    state: directory

- name: Ensure tmuxinator config dir exists
  file:
    path: "{{ home }}/.config/tmuxinator"
    state: directory

- name: Ensure ~/.claude exists
  file:
    path: "{{ home }}/.claude"
    state: directory
